development:
  adapter: postgresql
  encoding: unicode
  database: planductor_development
  pool: 5
  username: sebastian
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: planductor_test
  pool: 5
  username: sebastian
  password:
